import type { Metadata } from "next";
import { Geist, Geist_Mono, Bricolage_Grotesque, Figtree, Fira_Code } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const firaCode = Fira_Code({subsets:['menu','cyrillic','cyrillic-ext','greek','greek-ext','latin','latin-ext','symbols2'],weight:['300','400','500','600','700'],variable:'--font-fira-code'});

const figtree = Figtree({subsets:['menu','latin','latin-ext'],weight:['300','400','500','600','700','800','900'],variable:'--font-figtree'});

const bricolageGrotesque = Bricolage_Grotesque({subsets:['menu','latin','latin-ext','vietnamese'],weight:['200','300','400','500','600','700','800'],variable:'--font-bricolage-grotesque'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-bricolage-grotesque", "font-figtree", "font-fira-code", bricolageGrotesque.variable, figtree.variable, firaCode.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
